version: "3"
services:
 reverseproxy:
   image: aleweichandt/reverseproxy
   ports:
     - 8080:8080
   restart: always
   depends_on:
    - backend-user
    - backend-feed   
 backend-user:
  image: aleweichandt/udacity-restapi-user
  volumes:
   - $HOME/.aws:/root/.aws
  environment:
   DB_USER: $DB_USER
   DB_PASSWORD: $DB_PASSWORD 
   DB_NAME: $DB_NAME 
   DB_HOST: $DB_HOST 
   AWS_REGION: $AWS_REGION 
   AWS_PROFILE: $AWS_PROFILE 
   AWS_BUCKET: $AWS_BUCKET
   JWT_SECRET: $JWT_SECRET
   URL: "http://localhost:8100"
 backend-feed:
  image: aleweichandt/udacity-restapi-feed
  volumes:
   - $HOME/.aws:/root/.aws
  environment:
   DB_USER: $DB_USER
   DB_PASSWORD: $DB_PASSWORD 
   DB_NAME: $DB_NAME 
   DB_HOST: $DB_HOST 
   AWS_REGION: $AWS_REGION 
   AWS_PROFILE: $AWS_PROFILE 
   AWS_BUCKET: $AWS_BUCKET
   JWT_SECRET: $JWT_SECRET
   URL: "http://localhost:8100"
 frontend:
  image: aleweichandt/udacity-frontend
  ports:
   - "8100:80"